const backendDomain="http://localhost:8080"

const SummarApi={
signUp:{
    url:`${backendDomain}/api/signup`,
    method:"post"
},
signIn:{
    url:`${backendDomain}/api/signin`,
    method:"post"
},
userDetails:{
    url:`${backendDomain}/api/user-details`,
    method:"get"
},
logout_user:{
    url:`${backendDomain}/api/userLogout`,
    method:"get"
},
allUser:{
    url:`${backendDomain}/api/all-users`,
    method:"get"
},
updateUser:{
    url:`${backendDomain}/api/update-user`,
    method:"post"
},
uploadProduct:{
    url:`${backendDomain}/api/upload-product`,
    method:"post"
},
allProduct:{
    url:`${backendDomain}/api/get-products`,
    method:"get"
},
updateProduct:{
    url:`${backendDomain}/api/update-product`,
    method:"post"
},
ProductCategory:{
    url:`${backendDomain}/api/getProductsCategory`,
    method:"get"
},
categoryWiseProduct:{
    url:`${backendDomain}/api/category-product`,
    method:"post"
},
productDetails:{
    url:`${backendDomain}/api/product-details`,
    method:"post"
},
addToCartProduct:{
    url:`${backendDomain}/api/addToCart`,
    method:"post"
},
addToCartProductCount:{
    url:`${backendDomain}/api/countAddToCartProduct`,
    method:"get"
},
ProductCartInformation:{
    url:`${backendDomain}/api/ProductInCartInformation`,
    method:"get"
},
updateCartProduct:{
    url:`${backendDomain}/api/update-cart-product`,
    method:"post"
},
deleteCartProduct:{
    url:`${backendDomain}/api/delete-cart-product`,
    method:"post"
},
searchProduct:{
    url:`${backendDomain}/api/search`,
    method:"get"
},
filterProduct:{
    url:`${backendDomain}/api/filter-product`,
    method:"post"
},
payment:{
    url:`${backendDomain}/api/checkout`,
    method:"post"
},
orderPage:{
    url:`${backendDomain}/api/order-list`,
    method:"get"
}
}

export default SummarApi;